### ISSUE TITLE
Linux release of 2.1 is actually macOS

### ISSUE THREAD

**Issue by leximayfield** [lextoumbourou/goodhosts#12]
The Linux download for version 2.1.0 of this program isn't actually a linux executable, but instead a Mach-O 64-bit executable.

Not only that, but the executable as it stands doesn't even work on macOS High Sierra - I get a runtime error instead.

```
failed MSpanList_Insert 0x279000 0x26611aa86d8 0x0
fatal error: MSpanList_Insert
```

I think that the version of Go used to compile the program in the release is too out-of-date to work on High Sierra.

**Comment by luthermonson** [comment]
@AlexMax this has been solved in new release project in the Org I split this project off into. Please try this: https://github.com/goodhosts/cli/releases/tag/v1.0.0
